import fs from "node:fs";
import path from "node:path";
import {
  emptyManifest,
  loadManifest,
  optimizeAndStore,
  resolveImageConfig,
  saveManifest,
  type ManifestEntry,
  type StorageAdapter,
} from "@reptiles-ge/img-compression";
import { LocalStorageAdapter } from "@reptiles-ge/img-compression/storage";
import type { OptimizedImageEntry } from "@/data/optimizedImages";

const MAX_WIDTH = 2400;
const ADDITIONAL_WIDTHS = [400, 800, 1200];
const FORMATS = ["avif", "webp"] as const;
const MANIFEST_KEY = "image-manifest.json";
const GENERATED_REL = "src/data/optimizedImages.generated.ts";

const SPECIES_IMAGE_CONFIG = resolveImageConfig({
  maxWidth: MAX_WIDTH,
  additionalWidths: ADDITIONAL_WIDTHS,
});

export type OptimizeCatalogUpdate = {
  key: string;
  src: string;
  entry: ManifestEntry;
  asset: OptimizedImageEntry | null;
};

function compactAsset(
  key: string,
  entry: ManifestEntry,
  storage: StorageAdapter,
  prefix: string,
): OptimizedImageEntry | null {
  const widths = [...new Set(entry.derivatives.map((item) => item.width))].sort(
    (a, b) => a - b,
  );

  const byFormatWidth = new Map(
    entry.derivatives.map((item) => [`${item.format}@${item.width}`, item]),
  );

  const formats = FORMATS.filter((format) => {
    const widest = entry.derivatives
      .filter((item) => item.format === format)
      .reduce<ManifestEntry["derivatives"][number] | null>(
        (best, item) => (!best || item.width > best.width ? item : best),
        null,
      );
    if (!widest) return false;
    return widest.width < entry.width || widest.byteSize < entry.originalSize;
  });

  if (formats.length === 0) return null;

  const anchor = entry.derivatives[0];
  if (!anchor) throw new Error(`${key} has no derivatives.`);

  const anchorUrl = storage.urlFor(anchor.key);
  const anchorSuffix = `-${anchor.width}.${anchor.format}`;
  if (!anchorUrl.startsWith(prefix) || !anchorUrl.endsWith(anchorSuffix)) {
    throw new Error(
      `Derivative naming changed: ${anchorUrl} is not "${prefix}<path>${anchorSuffix}".`,
    );
  }
  const assetPath = anchorUrl.slice(prefix.length, -anchorSuffix.length);

  for (const width of widths) {
    for (const format of formats) {
      const derivative = byFormatWidth.get(`${format}@${width}`);
      if (!derivative) {
        throw new Error(`${key} is missing the ${width}px ${format} derivative.`);
      }
      const expected = `${prefix}${assetPath}-${width}.${format}`;
      if (storage.urlFor(derivative.key) !== expected) {
        throw new Error(
          `${key} derivative url ${storage.urlFor(derivative.key)} does not match ${expected}.`,
        );
      }
    }
  }

  return {
    path: assetPath,
    width: entry.width,
    height: entry.height,
    widths,
    formats: [...formats],
  };
}

export async function optimizeUploadedOriginal(input: {
  key: string;
  source: Buffer;
  src: string;
  storage: StorageAdapter;
}): Promise<OptimizeCatalogUpdate | null> {
  const result = await optimizeAndStore({
    key: input.key,
    source: input.source,
    storage: input.storage,
    config: SPECIES_IMAGE_CONFIG,
    storeOriginal: false,
  });
  if (!result.entry) return null;

  const entry = { ...result.entry, originalKey: input.key };
  const prefix = `${input.storage.urlFor(SPECIES_IMAGE_CONFIG.optimizedPrefix)}/`;
  const asset = compactAsset(input.key, entry, input.storage, prefix);
  return { key: input.key, src: input.src, entry, asset };
}

function upsertGeneratedFile(
  filePath: string,
  updates: Array<{ src: string; asset: OptimizedImageEntry }>,
) {
  const raw = fs.readFileSync(filePath, "utf8");
  const marker =
    "export const optimizedImages: Record<string, OptimizedImageEntry> = ";
  const start = raw.indexOf(marker);
  if (start < 0) {
    throw new Error("optimizedImages.generated.ts is not in the expected format");
  }
  const jsonPart = raw.slice(start + marker.length).trimEnd();
  if (!jsonPart.endsWith(";")) {
    throw new Error("optimizedImages.generated.ts is not in the expected format");
  }
  const images = JSON.parse(jsonPart.slice(0, -1)) as Record<
    string,
    OptimizedImageEntry
  >;
  for (const update of updates) {
    images[update.src] = update.asset;
  }
  const sorted = Object.fromEntries(
    Object.entries(images).sort(([a], [b]) => a.localeCompare(b)),
  );
  const prefixMatch = raw.match(/export const optimizedBaseUrl = ("[^"]+");/);
  const prefix = prefixMatch
    ? (JSON.parse(prefixMatch[1]) as string)
    : "https://cdn.reptiles.ge/optimized/";
  const next = `// Generated by scripts/optimize-images.ts — do not edit by hand.
import type { OptimizedImageEntry } from "./optimizedImages";

export const optimizedBaseUrl = ${JSON.stringify(prefix)};

export const optimizedImages: Record<string, OptimizedImageEntry> = ${JSON.stringify(
    sorted,
    null,
    2,
  )};
`;
  fs.writeFileSync(filePath, next);
}

export async function applyOptimizeCatalog(
  repoRoot: string,
  updates: OptimizeCatalogUpdate[],
) {
  if (updates.length === 0) return;

  const manifestStorage = new LocalStorageAdapter({
    root: path.join(repoRoot, "src/data"),
  });
  const manifest = await loadManifest(manifestStorage, MANIFEST_KEY);
  const entries = { ...manifest.entries };
  for (const update of updates) {
    entries[update.key] = update.entry;
  }
  await saveManifest(manifestStorage, MANIFEST_KEY, {
    ...emptyManifest(),
    entries,
  });

  const assets = updates.filter(
    (update): update is OptimizeCatalogUpdate & { asset: OptimizedImageEntry } =>
      update.asset !== null,
  );
  if (assets.length === 0) return;
  upsertGeneratedFile(path.join(repoRoot, GENERATED_REL), assets);
}
