import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  cacheDir: path.resolve(__dirname, "node_modules/.vite"),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
      "next-intl/navigation": path.resolve(
        __dirname,
        "tests/stubs/next-intl-navigation.ts",
      ),
      "next/navigation": path.resolve(
        __dirname,
        "tests/stubs/next-navigation.ts",
      ),
    },
  },
  test: {
    coverage: {
      exclude: [
        "src/**/*.test.{ts,tsx}",
        "src/**/*.d.ts",
        "src/**/*.generated.ts",
        "src/content/**",
        "src/components/AboutPage.tsx",
        "src/components/AmphibianSpeciesIndexPage.tsx",
        "src/components/AnalyticsPageContext.tsx",
        "src/components/AnchoredHeading.tsx",
        "src/components/AuthorGallery.tsx",
        "src/components/AuthorIndexPage.tsx",
        "src/components/AuthorPage.tsx",
        "src/components/AuthorPageParts.tsx",
        "src/components/AxeDevConsole.tsx",
        "src/components/BiologyExpandable.tsx",
        "src/components/CatalogSpeciesIndexPage.tsx",
        "src/components/ClientMessagesProvider.tsx",
        "src/components/ClusterContentSection.tsx",
        "src/components/ClusterGuidePage.tsx",
        "src/components/ClusterNumberedSteps.tsx",
        "src/components/ClusterPageFrame.tsx",
        "src/components/ClusterPathCard.tsx",
        "src/components/ConflictGuideSections.tsx",
        "src/components/ContactMailto.tsx",
        "src/components/ContactPage.tsx",
        "src/components/ContentAttribution.tsx",
        "src/components/CoverImage.tsx",
        "src/components/CoverImagePreload.tsx",
        "src/components/DangerousAnimalsPage.tsx",
        "src/components/DarevskiaGuidePage.tsx",
        "src/components/ErrorFallback.tsx",
        "src/components/FinalCTA.tsx",
        "src/components/Footer.tsx",
        "src/components/FooterGate.tsx",
        "src/components/FrogSpeciesIndexPage.tsx",
        "src/components/GoogleTagManager.tsx",
        "src/components/GroupHubFaqSection.tsx",
        "src/components/GroupHubGuides.tsx",
        "src/components/GroupHubHero.tsx",
        "src/components/GroupHubOverview.tsx",
        "src/components/GroupHubPage.tsx",
        "src/components/GroupHubRegionsMap.tsx",
        "src/components/GroupHubSectionHeading.tsx",
        "src/components/GroupHubSpeciesList.tsx",
        "src/components/GuideArticlePage.tsx",
        "src/components/GuideArticleRelatedBlock.tsx",
        "src/components/GuideFaqItems.tsx",
        "src/components/GuideSources.tsx",
        "src/components/GuideSpeciesSection.tsx",
        "src/components/Hero.tsx",
        "src/components/HomeSeo.tsx",
        "src/components/InkHeroBreadcrumb.tsx",
        "src/components/IntentPrefetchLink.tsx",
        "src/components/IntlProvider.tsx",
        "src/components/JsonLd.tsx",
        "src/components/LanguageSwitcher.tsx",
        "src/components/LegalDocumentPage.tsx",
        "src/components/LizardComparePage.tsx",
        "src/components/LizardHousePage.tsx",
        "src/components/LizardIdentifyPage.tsx",
        "src/components/LizardSpeciesIndexPage.tsx",
        "src/components/LocaleSwitchProvider.tsx",
        "src/components/LocalizedLink.tsx",
        "src/components/Logo.tsx",
        "src/components/LogoPreload.tsx",
        "src/components/LookalikePair.tsx",
        "src/components/LookalikePairGrid.tsx",
        "src/components/MammalBearPage.tsx",
        "src/components/MammalJackalYardPage.tsx",
        "src/components/MotionLazy.tsx",
        "src/components/Navbar.tsx",
        "src/components/NavbarChrome.tsx",
        "src/components/NavbarMenu.tsx",
        "src/components/NavigationProgress.tsx",
        "src/components/NewsArticleCard.tsx",
        "src/components/NewsArticlePage.tsx",
        "src/components/NewsIndexPage.tsx",
        "src/components/NewsRelatedBlock.tsx",
        "src/components/NewsRichText.tsx",
        "src/components/NotFoundAnalytics.tsx",
        "src/components/NotFoundBoundary.tsx",
        "src/components/NotFoundContent.tsx",
        "src/components/NotFoundShell.tsx",
        "src/components/OverlayPanel.tsx",
        "src/components/OverlayPanelImpl.tsx",
        "src/components/PhotoCreditCaption.tsx",
        "src/components/QuizCopyContext.tsx",
        "src/components/QuizCover.tsx",
        "src/components/QuizCoverPicture.tsx",
        "src/components/QuizCtaLink.tsx",
        "src/components/QuizIntroOverlay.tsx",
        "src/components/QuizLanding.tsx",
        "src/components/QuizPlayer.tsx",
        "src/components/QuizPracticeCta.tsx",
        "src/components/QuizResultOverlay.tsx",
        "src/components/QuizRound.tsx",
        "src/components/QuizStage.tsx",
        "src/components/QuizzesPage.tsx",
        "src/components/RegionProfile.tsx",
        "src/components/RegionsIndex.tsx",
        "src/components/RelatedGuideCards.tsx",
        "src/components/RiskLevelList.tsx",
        "src/components/RiskToHumansHero.tsx",
        "src/components/RiskToHumansPage.tsx",
        "src/components/SafetyGuideSections.tsx",
        "src/components/ScreenReaderBreadcrumb.tsx",
        "src/components/ScrollToTop.tsx",
        "src/components/SectionNav.tsx",
        "src/components/SiteRating.tsx",
        "src/components/SiteRatingMascot.tsx",
        "src/components/SkipLink.tsx",
        "src/components/SnakeIdentifyPage.tsx",
        "src/components/SnakeLargestPage.tsx",
        "src/components/SnakeRangePage.tsx",
        "src/components/SnakeSpeciesIndexPage.tsx",
        "src/components/SnakesInYardHero.tsx",
        "src/components/SnakesInYardPage.tsx",
        "src/components/SnakesInYardSections.tsx",
        "src/components/SocialGlyphs.tsx",
        "src/components/SourceLink.tsx",
        "src/components/SpeciesActionBar.tsx",
        "src/components/SpeciesDanger.tsx",
        "src/components/SpeciesFaqItems.tsx",
        "src/components/SpeciesFaqSection.tsx",
        "src/components/SpeciesGallery.tsx",
        "src/components/SpeciesGalleryLightbox.tsx",
        "src/components/SpeciesGuideRow.tsx",
        "src/components/SpeciesIdentification.tsx",
        "src/components/SpeciesIndexTable.tsx",
        "src/components/SpeciesInlineLink.tsx",
        "src/components/SpeciesLookalikeList.tsx",
        "src/components/SpeciesOverviewText.tsx",
        "src/components/SpeciesProfile.tsx",
        "src/components/SpeciesProfileBody.tsx",
        "src/components/SpeciesProfileFacts.tsx",
        "src/components/SpeciesProfileHero.tsx",
        "src/components/SpeciesProfileQuiz.tsx",
        "src/components/SpeciesQuizTeaser.tsx",
        "src/components/SpeciesScientificNameCopy.tsx",
        "src/components/SpeciesSearch.tsx",
        "src/components/SpeciesSearchDesktopPanel.tsx",
        "src/components/SpeciesSearchEmpty.tsx",
        "src/components/SpeciesSearchField.tsx",
        "src/components/SpeciesSearchFilterBar.tsx",
        "src/components/SpeciesSearchGroupLabel.tsx",
        "src/components/SpeciesSearchResults.tsx",
        "src/components/SpeciesSearchRow.tsx",
        "src/components/SpeciesViewTracker.tsx",
        "src/components/SpeciesVoicePlayer.tsx",
        "src/components/SpiderBitePage.tsx",
        "src/components/SpiderVenomousPage.tsx",
        "src/components/ThemeProvider.tsx",
        "src/components/ThemeToggle.tsx",
        "src/components/TopGeCounter.tsx",
        "src/components/TurtleIdentifyChooser.tsx",
        "src/components/TurtleIdentifyFlow.tsx",
        "src/components/TurtleIdentifyMatrix.tsx",
        "src/components/TurtleIdentifyPage.tsx",
        "src/components/TurtlesHubSections.tsx",
        "src/components/VenomousSnakesCompare.tsx",
        "src/components/VenomousSnakesCta.tsx",
        "src/components/VenomousSnakesGuides.tsx",
        "src/components/VenomousSnakesHero.tsx",
        "src/components/VenomousSnakesPage.tsx",
        "src/components/VenomousSnakesSpecies.tsx",
        "src/components/admin/AdminCdnUpload.tsx",
        "src/components/admin/AdminCoverCrop.tsx",
        "src/components/admin/AdminCoverPreview.tsx",
        "src/components/admin/AdminGalleryReorder.tsx",
        "src/components/admin/AdminSpeciesCreate.tsx",
        "src/components/admin/AdminSpeciesEditor.tsx",
        "src/components/admin/AdminSpeciesList.tsx",
        "src/components/admin/SelectionContentEditor.tsx",
        "src/components/admin/SpeciesPageAnalysis.tsx",
        "src/components/conflictGuideConfig.ts",
        "src/components/home/HomeContributors.tsx",
        "src/components/home/HomeFeatured.tsx",
        "src/components/home/HomeField.tsx",
        "src/components/home/HomeFooter.tsx",
        "src/components/home/HomeFresh.tsx",
        "src/components/home/HomeGroups.tsx",
        "src/components/home/HomeGuides.tsx",
        "src/components/home/HomeSafetyStrip.tsx",
        "src/components/home/TrackedSpeciesLink.tsx",
        "src/components/map/GeorgiaMap.tsx",
        "src/components/map/GeorgiaMapStatic.tsx",
        "src/components/map/HalyomorphaRangeLedger.tsx",
        "src/components/map/HalyomorphaRangeMap.tsx",
        "src/components/map/HalyomorphaRangeMapClient.tsx",
        "src/components/map/HalyomorphaRangeMapEngine.ts",
        "src/components/map/HalyomorphaRangeMapTypes.ts",
        "src/components/map/MapExplorer.tsx",
        "src/components/map/RangeHatch.tsx",
        "src/components/map/Region.tsx",
        "src/components/map/RegionDetailsPanel.tsx",
        "src/components/map/RegionTooltip.tsx",
        "src/components/map/SpeciesCard.tsx",
        "src/components/map/SpeciesRangeMap.tsx",
        "src/components/safetyGuideConfig.ts",
        "src/components/species-atlas/AtlasAbout.tsx",
        "src/components/species-atlas/AtlasBrowse.tsx",
        "src/components/species-atlas/AtlasFilterSheet.tsx",
        "src/components/species-atlas/AtlasHero.tsx",
        "src/components/species-atlas/AtlasMap.tsx",
        "src/components/species-atlas/AtlasRecent.tsx",
        "src/components/species-atlas/AtlasSeo.tsx",
        "src/components/species-atlas/AtlasSpeciesCard.tsx",
        "src/components/species-atlas/AtlasSpeciesGrid.tsx",
        "src/components/species-atlas/SpeciesAtlas.tsx",
        "src/components/species-atlas/atlasOptions.ts",
        "src/app/**/page.tsx",
        "src/app/**/layout.tsx",
        "src/app/**/not-found.tsx",
        "src/app/**/error.tsx",
        "src/app/**/loading.tsx",
        "src/app/**/opengraph-image.tsx",
        "src/app/admin/**",
        "src/app/api/admin/**",
        "src/app/api/dev/**",
        "src/lib/admin*.ts",
        "src/lib/contentEditor*.ts",
        "src/lib/speciesPageAnalysis.ts",
        "src/lib/speciesTextProcessing.ts",
        "src/lib/quizDraft.ts",
        "src/lib/axeDev.ts",
        "src/lib/codexProcess.ts",
        "src/lib/create*Route.tsx",
        "src/lib/focusTrap.ts",
        "src/lib/use*.ts",
        "src/instrumentation*.ts",
        "src/worker.ts",
        "src/app/RootDocument.tsx",
        "src/i18n/request.ts",
      ],
      include: ["src/**/*.{ts,tsx}"],
      provider: "v8",
      reporter: ["text-summary", "json-summary"],
      reportsDirectory: "coverage",
      thresholds: { branches: 82, functions: 91, lines: 93, statements: 90 },
    },
    projects: [
      {
        extends: true,
        test: {
          environment: "node",
          fileParallelism: false,
          include: ["src/**/*.test.ts"],
          name: "node",
          pool: "forks",
          server: { deps: { inline: ["next-intl"] } },
          setupFiles: ["tests/setup/msw.ts"],
          testTimeout: 20_000,
        },
      },
      {
        extends: true,
        test: {
          environment: "happy-dom",
          fileParallelism: false,
          include: ["src/**/*.test.tsx"],
          name: "dom",
          pool: "forks",
          server: { deps: { inline: ["next-intl"] } },
          setupFiles: ["tests/setup/dom.ts"],
          testTimeout: 20_000,
        },
      },
    ],
  },
});
