import fs from "node:fs";
import path from "node:path";

import type { RegionPathId } from "../src/data/georgia-paths";
import type { SpeciesFieldRecord } from "../src/data/speciesTypes";
import type { HalyomorphaRegionOccurrenceResponse } from "../src/lib/halyomorphaOccurrenceApi";

import { HALYOMORPHA_RANGE_GEOJSON } from "../src/data/halyomorphaRangeRegions";
import { getCatalogSpecies } from "../src/data/species";
import { localizeSpecies } from "../src/i18n/localizeSpecies";
import { routing } from "../src/i18n/routing";
import {
  confirmedRecordThresholdForSpecies,
  getHalyomorphaFieldRecords,
  getHalyomorphaOccurrenceSummary,
  getHalyomorphaRegionRecords,
  type HalyomorphaOccurrenceSummary,
  occurrenceStatusForCount,
} from "../src/lib/halyomorphaOccurrences";
import { getSpeciesHeroSources } from "../src/lib/speciesContent";

const root = process.cwd();
const recordsFile = path.join(root, "src/data/fieldRecords.generated.json");
const summariesFile = path.join(
  root,
  "src/data/occurrenceSummaries.generated.ts",
);
const publicDir = path.join(root, "public/data/occurrences");

const fieldRecordsById = JSON.parse(
  fs.readFileSync(recordsFile, "utf8"),
) as Record<string, SpeciesFieldRecord[]>;

const regionIds: RegionPathId[] = HALYOMORPHA_RANGE_GEOJSON.features.map(
  (feature) => feature.properties.id,
);

type SummaryEntry = {
  base: HalyomorphaOccurrenceSummary;
  locales?: Record<string, HalyomorphaOccurrenceSummary>;
};

const summaries: Record<string, SummaryEntry> = {};

function withoutRegionNames(summary: HalyomorphaOccurrenceSummary) {
  return {
    ...summary,
    recordsByRegion: summary.recordsByRegion.map((region) => ({
      ...region,
      name: region.id,
    })),
  };
}

fs.rmSync(publicDir, { force: true, recursive: true });

let files = 0;
for (const raw of getCatalogSpecies()) {
  const fieldRecords = fieldRecordsById[raw.id];
  if (!fieldRecords) continue;
  const threshold = confirmedRecordThresholdForSpecies(raw.id);

  for (const locale of routing.locales) {
    const item = localizeSpecies(raw, locale);
    const pageRecords = getHalyomorphaFieldRecords({
      fieldRecords,
      gallery: getSpeciesHeroSources(item).gallery,
      locale,
      speciesName: item.commonName,
    });
    const summary = withoutRegionNames(
      getHalyomorphaOccurrenceSummary(pageRecords, locale, threshold),
    );
    const entry = summaries[raw.id];
    if (!entry) {
      summaries[raw.id] = { base: summary };
    } else if (JSON.stringify(entry.base) !== JSON.stringify(summary)) {
      entry.locales = { ...entry.locales, [locale]: summary };
    }

    const records = getHalyomorphaFieldRecords({
      fieldRecords,
      gallery: raw.gallery,
      locale,
      speciesName: raw.commonName,
    });
    if (records.length === 0) continue;

    const regions: Partial<
      Record<RegionPathId, HalyomorphaRegionOccurrenceResponse>
    > = {};
    for (const regionId of regionIds) {
      const regionRecords = getHalyomorphaRegionRecords(records, regionId);
      const summary = getHalyomorphaOccurrenceSummary(
        regionRecords,
        locale,
        threshold,
      );
      regions[regionId] = {
        records: regionRecords,
        region: summary.recordsByRegion[0] ?? {
          count: 0,
          iNaturalistRecordCount: 0,
          id: regionId,
          name: regionId,
          photoRecordCount: 0,
          status: occurrenceStatusForCount(0),
        },
      };
    }

    const out = path.join(publicDir, raw.id, `${locale}.json`);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, JSON.stringify({ regions }), "utf8");
    files += 1;
  }
}

const source = `/* eslint-disable */
// Generated by scripts/compile-occurrences.ts — do not edit by hand.
import type { HalyomorphaOccurrenceSummary } from "../lib/halyomorphaOccurrences";

export const speciesIdsWithFieldRecords: readonly string[] = ${JSON.stringify(Object.keys(fieldRecordsById).sort())};

export const occurrenceSummaries: Record<string, { base: HalyomorphaOccurrenceSummary; locales?: Partial<Record<string, HalyomorphaOccurrenceSummary>> }> = ${JSON.stringify(summaries)};
`;
fs.writeFileSync(summariesFile, source, "utf8");

const overrides = Object.values(summaries).filter((entry) => entry.locales);
console.log(
  `Compiled occurrence summaries for ${Object.keys(summaries).length} species (${overrides.length} with locale overrides) → ${summariesFile}`,
);
console.log(`Wrote ${files} occurrence files → ${publicDir}`);
