import fs from "node:fs";
import path from "node:path";

import { routing } from "../src/i18n/routing";

const generatedSpecies = path.join(
  process.cwd(),
  "src/data/species.generated.ts",
);
const outFile = path.join(process.cwd(), "src/data/search-index.generated.ts");

async function main() {
  if (!fs.existsSync(generatedSpecies)) {
    throw new Error("Run species:compile before search:compile");
  }

  const { buildSearchIndex } = await import("../src/lib/searchIndexBuild");

  const searchIndexes = Object.fromEntries(
    routing.locales.map((locale) => [locale, buildSearchIndex(locale)]),
  );

  const contents = `/* eslint-disable */
// Generated by scripts/compile-search.ts — do not edit by hand.
import type { AppLocale } from "@/i18n/routing";
import type { SearchDocument } from "@/lib/siteSearch";

export const searchIndexes: Record<AppLocale, SearchDocument[]> = ${JSON.stringify(searchIndexes)};

export function getSearchIndex(locale: AppLocale): SearchDocument[] {
  return searchIndexes[locale];
}
`;

  fs.writeFileSync(outFile, contents);
  console.log(`Wrote ${outFile}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
