import fs from "node:fs";
import path from "node:path";

import type { AppLocale } from "../src/i18n/routing";

import { routing } from "../src/i18n/routing";

const generatedSpecies = path.join(
  process.cwd(),
  "src/data/species.generated.ts",
);
const legacyOutFile = path.join(
  process.cwd(),
  "src/data/search-index.generated.ts",
);

function localeOutFile(locale: AppLocale) {
  return path.join(
    process.cwd(),
    `src/data/search-index.${locale}.generated.ts`,
  );
}

async function main() {
  if (!fs.existsSync(generatedSpecies)) {
    throw new Error("Run species:compile before search:compile");
  }

  const { buildSearchIndex } = await import("../src/lib/searchIndexBuild");

  const banner = `/* eslint-disable */
// Generated by scripts/compile-search.ts — do not edit by hand.
`;

  for (const locale of routing.locales) {
    const searchDocuments = buildSearchIndex(locale);
    const contents = `${banner}import type { SearchDocument } from "@/lib/siteSearch";

export const searchDocuments: SearchDocument[] = ${JSON.stringify(searchDocuments)};
`;
    const outFile = localeOutFile(locale);
    fs.writeFileSync(outFile, contents);
    console.log(`Wrote ${searchDocuments.length} ${locale} docs → ${outFile}`);
  }

  if (fs.existsSync(legacyOutFile)) {
    fs.unlinkSync(legacyOutFile);
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
