import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import type {
  DangerLevel,
  GalleryImage,
  PhotoCredit,
  Species,
  SpeciesFaq,
  SpeciesStat,
} from "../src/data/species";

const contentRoot = path.join(process.cwd(), "src/content/species");
const outFile = path.join(process.cwd(), "src/data/species.generated.ts");

type SpeciesFrontmatter = {
  id: string;
  commonName: string;
  scientificName: string;
  genus: string;
  family: string;
  location: string;
  description: string;
  overview: string;
  habitat: string;
  diet: string;
  behavior: string;
  conservation: string;
  danger: DangerLevel;
  image: string;
  imageCredit?: PhotoCredit;
  mobileImage?: string;
  mobileImageCredit?: PhotoCredit;
  gallery: GalleryImage[];
  stats: SpeciesStat[];
  facts: string[];
  faq?: SpeciesFaq[];
};

function readSpeciesMdx(filePath: string): Species {
  const raw = fs.readFileSync(filePath, "utf8");
  const { data } = matter(raw);
  const fm = data as SpeciesFrontmatter;

  if (!fm.id || !fm.commonName || !fm.scientificName) {
    throw new Error(`Invalid species frontmatter: ${filePath}`);
  }

  return {
    id: fm.id,
    commonName: fm.commonName,
    scientificName: fm.scientificName,
    genus: fm.genus,
    family: fm.family,
    location: fm.location,
    description: fm.description,
    overview: fm.overview,
    habitat: fm.habitat,
    diet: fm.diet,
    behavior: fm.behavior,
    conservation: fm.conservation,
    danger: fm.danger,
    image: fm.image,
    ...(fm.imageCredit ? { imageCredit: fm.imageCredit } : {}),
    ...(fm.mobileImage ? { mobileImage: fm.mobileImage } : {}),
    ...(fm.mobileImageCredit
      ? { mobileImageCredit: fm.mobileImageCredit }
      : {}),
    gallery: fm.gallery ?? [],
    stats: fm.stats ?? [],
    facts: fm.facts ?? [],
    ...(fm.faq ? { faq: fm.faq } : {}),
  };
}

function toTranslation(item: Species) {
  return {
    commonName: item.commonName,
    location: item.location,
    description: item.description,
    overview: item.overview,
    habitat: item.habitat,
    diet: item.diet,
    behavior: item.behavior,
    conservation: item.conservation,
    stats: item.stats,
    facts: item.facts,
    ...(item.faq ? { faq: item.faq } : {}),
  };
}

if (!fs.existsSync(contentRoot)) {
  throw new Error(`Missing content directory: ${contentRoot}`);
}

const ids = fs
  .readdirSync(contentRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort((a, b) => a.localeCompare(b));

const species: Species[] = [];
const speciesEn: Record<string, ReturnType<typeof toTranslation>> = {};

for (const id of ids) {
  const kaPath = path.join(contentRoot, id, "ka.mdx");
  const enPath = path.join(contentRoot, id, "en.mdx");

  if (!fs.existsSync(kaPath)) {
    throw new Error(`Missing ka.mdx for species: ${id}`);
  }

  const ka = readSpeciesMdx(kaPath);
  if (ka.id !== id) {
    throw new Error(`Folder/id mismatch: folder=${id} frontmatter=${ka.id}`);
  }
  species.push(ka);

  if (fs.existsSync(enPath)) {
    speciesEn[id] = toTranslation(readSpeciesMdx(enPath));
  }
}

const banner = `/* eslint-disable */
// Generated by scripts/compile-species.ts — do not edit by hand.
`;

const source = `${banner}import type { Species, SpeciesTranslation } from "./species";

export const species: Species[] = ${JSON.stringify(species, null, 2)};

export const speciesEn: Record<string, SpeciesTranslation> = ${JSON.stringify(speciesEn, null, 2)};
`;

fs.writeFileSync(outFile, source, "utf8");
console.log(`Compiled ${species.length} species → ${outFile}`);
