/* eslint-disable */
// Generated by scripts/optimize-images.ts — do not edit by hand.
import type { OptimizedImageAsset } from "./optimizedImages";

export const optimizedImages: Record<string, OptimizedImageAsset> = {
  "https://cdn.reptiles.ge/canis-aureus-bukvic-1.jpg": {
    "width": 2400,
    "height": 1600,
    "sources": [
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-bukvic-1-1200.avif",
        "width": 1200,
        "height": 800
      },
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-bukvic-1-2400.avif",
        "width": 2400,
        "height": 1600
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-bukvic-1-1200.webp",
        "width": 1200,
        "height": 800
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-bukvic-1-2400.webp",
        "width": 2400,
        "height": 1600
      }
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-danube-1.jpg": {
    "width": 2400,
    "height": 1620,
    "sources": [
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-danube-1-1200.avif",
        "width": 1200,
        "height": 810
      },
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-danube-1-2400.avif",
        "width": 2400,
        "height": 1620
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-danube-1-1200.webp",
        "width": 1200,
        "height": 810
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-danube-1-2400.webp",
        "width": 2400,
        "height": 1620
      }
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-kerkini-1.jpg": {
    "width": 2130,
    "height": 1420,
    "sources": [
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-kerkini-1-1200.avif",
        "width": 1200,
        "height": 800
      },
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-kerkini-1-2130.avif",
        "width": 2130,
        "height": 1420
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-kerkini-1-1200.webp",
        "width": 1200,
        "height": 800
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-kerkini-1-2130.webp",
        "width": 2130,
        "height": 1420
      }
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-lagodekhi-1.jpg": {
    "width": 1024,
    "height": 738,
    "sources": [
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-lagodekhi-1-1024.avif",
        "width": 1024,
        "height": 738
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-lagodekhi-1-1024.webp",
        "width": 1024,
        "height": 738
      }
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-stankovic-1.jpg": {
    "width": 2290,
    "height": 2489,
    "sources": [
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-stankovic-1-1200.avif",
        "width": 1200,
        "height": 1304
      },
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-stankovic-1-2290.avif",
        "width": 2290,
        "height": 2489
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-stankovic-1-1200.webp",
        "width": 1200,
        "height": 1304
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-stankovic-1-2290.webp",
        "width": 2290,
        "height": 2489
      }
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-yarkon-1.jpg": {
    "width": 2400,
    "height": 1711,
    "sources": [
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-yarkon-1-1200.avif",
        "width": 1200,
        "height": 856
      },
      {
        "format": "avif",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-yarkon-1-2400.avif",
        "width": 2400,
        "height": 1711
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-yarkon-1-1200.webp",
        "width": 1200,
        "height": 856
      },
      {
        "format": "webp",
        "url": "https://cdn.reptiles.ge/optimized/canis-aureus-yarkon-1-2400.webp",
        "width": 2400,
        "height": 1711
      }
    ]
  }
};
