// Generated by scripts/optimize-images.ts — do not edit by hand.
import type { OptimizedImageEntry } from "./optimizedImages";

export const optimizedBaseUrl = "https://cdn.reptiles.ge/optimized/";

export const optimizedImages: Record<string, OptimizedImageEntry> = {
  "https://cdn.reptiles.ge/ablepharus-pannonicus-2.jpg": {
    "path": "ablepharus-pannonicus-2",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ablepharus-pannonicus-3.jpg": {
    "path": "ablepharus-pannonicus-3",
    "width": 522,
    "height": 522,
    "widths": [
      400,
      522
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ablepharus-pannonicus.jpg": {
    "path": "ablepharus-pannonicus",
    "width": 1944,
    "height": 1944,
    "widths": [
      400,
      800,
      1200,
      1944
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/accipiter-nisus-knoch-flight.jpg": {
    "path": "accipiter-nisus-knoch-flight",
    "width": 900,
    "height": 601,
    "widths": [
      400,
      800,
      900
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/accipiter-nisus-mecnarowski-1.jpg": {
    "path": "accipiter-nisus-mecnarowski-1",
    "width": 850,
    "height": 607,
    "widths": [
      400,
      800,
      850
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/accipiter-nisus-sharp-female.jpg": {
    "path": "accipiter-nisus-sharp-female",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/accipiter-nisus-sharp-male.jpg": {
    "path": "accipiter-nisus-sharp-male",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/accipiter-nisus-zjeroen-1.jpg": {
    "path": "accipiter-nisus-zjeroen-1",
    "width": 1000,
    "height": 1500,
    "widths": [
      400,
      800,
      1000
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-2.jpg": {
    "path": "anguis-colchica-2",
    "width": 1200,
    "height": 658,
    "widths": [
      400,
      800,
      1200
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-3.jpg": {
    "path": "anguis-colchica-3",
    "width": 2048,
    "height": 1152,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-mobile.jpg": {
    "path": "anguis-colchica-mobile",
    "width": 2048,
    "height": 1356,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-sandro-1.jpg": {
    "path": "anguis-colchica-sandro-1",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-sandro-2.jpg": {
    "path": "anguis-colchica-sandro-2",
    "width": 1024,
    "height": 749,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-sandro-3.jpg": {
    "path": "anguis-colchica-sandro-3",
    "width": 1024,
    "height": 760,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-zauri-1.jpg": {
    "path": "anguis-colchica-zauri-1",
    "width": 1024,
    "height": 738,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-zauri-2.jpg": {
    "path": "anguis-colchica-zauri-2",
    "width": 1024,
    "height": 612,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica-zauri-3.jpg": {
    "path": "anguis-colchica-zauri-3",
    "width": 1024,
    "height": 731,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/anguis-colchica.jpg": {
    "path": "anguis-colchica",
    "width": 1000,
    "height": 668,
    "widths": [
      400,
      800,
      1000
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/bufo-verrucosissimus-2.jpg": {
    "path": "bufo-verrucosissimus-2",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufo-verrucosissimus-3.jpg": {
    "path": "bufo-verrucosissimus-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufo-verrucosissimus-zauri-1.jpg": {
    "path": "bufo-verrucosissimus-zauri-1",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufo-verrucosissimus-zauri-2.jpg": {
    "path": "bufo-verrucosissimus-zauri-2",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufo-verrucosissimus-zauri-3.jpg": {
    "path": "bufo-verrucosissimus-zauri-3",
    "width": 1024,
    "height": 681,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufo-verrucosissimus.jpg": {
    "path": "bufo-verrucosissimus",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufotes-viridis-2.jpg": {
    "path": "bufotes-viridis-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufotes-viridis-3.jpg": {
    "path": "bufotes-viridis-3",
    "width": 1200,
    "height": 1600,
    "widths": [
      400,
      800,
      1200
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufotes-viridis-armen-1.jpg": {
    "path": "bufotes-viridis-armen-1",
    "width": 687,
    "height": 1024,
    "widths": [
      400,
      687
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufotes-viridis-ioane-1.jpg": {
    "path": "bufotes-viridis-ioane-1",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufotes-viridis-ioane-2.jpg": {
    "path": "bufotes-viridis-ioane-2",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufotes-viridis-lasha-1.jpg": {
    "path": "bufotes-viridis-lasha-1",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufotes-viridis-zakro-1.jpg": {
    "path": "bufotes-viridis-zakro-1",
    "width": 766,
    "height": 1024,
    "widths": [
      400,
      766
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/bufotes-viridis.jpg": {
    "path": "bufotes-viridis",
    "width": 2000,
    "height": 1335,
    "widths": [
      400,
      800,
      1200,
      2000
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/buteo-buteo-lukasik-1.jpg": {
    "path": "buteo-buteo-lukasik-1",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/buteo-buteo-serbia-1.jpg": {
    "path": "buteo-buteo-serbia-1",
    "width": 1194,
    "height": 896,
    "widths": [
      400,
      800,
      1194
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/buteo-buteo-sevan-1.jpg": {
    "path": "buteo-buteo-sevan-1",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/buteo-buteo-sharp-vulpinus.jpg": {
    "path": "buteo-buteo-sharp-vulpinus",
    "width": 2400,
    "height": 3601,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/buteo-buteo-szczepanek-1.jpg": {
    "path": "buteo-buteo-szczepanek-1",
    "width": 369,
    "height": 550,
    "widths": [
      369
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/buteo-buteo-yerpo-juv.jpg": {
    "path": "buteo-buteo-yerpo-juv",
    "width": 1920,
    "height": 1758,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-bukvic-1.jpg": {
    "path": "canis-aureus-bukvic-1",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-danube-1.jpg": {
    "path": "canis-aureus-danube-1",
    "width": 2400,
    "height": 1620,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-kerkini-1.jpg": {
    "path": "canis-aureus-kerkini-1",
    "width": 2130,
    "height": 1420,
    "widths": [
      400,
      800,
      1200,
      2130
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-lagodekhi-1.jpg": {
    "path": "canis-aureus-lagodekhi-1",
    "width": 1024,
    "height": 738,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-stankovic-1.jpg": {
    "path": "canis-aureus-stankovic-1",
    "width": 2290,
    "height": 2489,
    "widths": [
      400,
      800,
      1200,
      2290
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-aureus-yarkon-1.jpg": {
    "path": "canis-aureus-yarkon-1",
    "width": 2400,
    "height": 1711,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-lupus-eurasian-1.jpg": {
    "path": "canis-lupus-eurasian-1",
    "width": 2400,
    "height": 1859,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-lupus-gareja-1.jpg": {
    "path": "canis-lupus-gareja-1",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-lupus-innsbruck-1.jpg": {
    "path": "canis-lupus-innsbruck-1",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-lupus-pescheray-1.jpg": {
    "path": "canis-lupus-pescheray-1",
    "width": 2400,
    "height": 2777,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-lupus-portrait-1.jpg": {
    "path": "canis-lupus-portrait-1",
    "width": 2048,
    "height": 3072,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-lupus-sainte-croix-1.jpg": {
    "path": "canis-lupus-sainte-croix-1",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/canis-lupus-tracks-1.jpg": {
    "path": "canis-lupus-tracks-1",
    "width": 2400,
    "height": 1800,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/capreolus-capreolus-antlers-1.jpg": {
    "path": "capreolus-capreolus-antlers-1",
    "width": 1914,
    "height": 1277,
    "widths": [
      400,
      800,
      1200,
      1914
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/capreolus-capreolus-buck-1.jpg": {
    "path": "capreolus-capreolus-buck-1",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/capreolus-capreolus-fawn-1.jpg": {
    "path": "capreolus-capreolus-fawn-1",
    "width": 1920,
    "height": 1920,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/capreolus-capreolus-male-1.jpg": {
    "path": "capreolus-capreolus-male-1",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/capreolus-capreolus-portrait-1.jpg": {
    "path": "capreolus-capreolus-portrait-1",
    "width": 1920,
    "height": 2560,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/capreolus-capreolus-running-1.jpg": {
    "path": "capreolus-capreolus-running-1",
    "width": 1920,
    "height": 1329,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/capreolus-capreolus-summer-1.jpg": {
    "path": "capreolus-capreolus-summer-1",
    "width": 1920,
    "height": 1326,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/capreolus-capreolus-winter-1.jpg": {
    "path": "capreolus-capreolus-winter-1",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-3.webp": {
    "path": "coronella-austriaca-3",
    "width": 2200,
    "height": 1466,
    "widths": [
      400,
      800,
      1200,
      2200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-4.webp": {
    "path": "coronella-austriaca-4",
    "width": 2200,
    "height": 1650,
    "widths": [
      400,
      800,
      1200,
      2200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-5.webp": {
    "path": "coronella-austriaca-5",
    "width": 2200,
    "height": 1466,
    "widths": [
      400,
      800,
      1200,
      2200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-6.webp": {
    "path": "coronella-austriaca-6",
    "width": 2200,
    "height": 1441,
    "widths": [
      400,
      800,
      1200,
      2200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-7.webp": {
    "path": "coronella-austriaca-7",
    "width": 2200,
    "height": 1237,
    "widths": [
      400,
      800,
      1200,
      2200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-sandro-1.jpg": {
    "path": "coronella-austriaca-sandro-1",
    "width": 1393,
    "height": 960,
    "widths": [
      400,
      800,
      1200,
      1393
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-sandro-2.jpg": {
    "path": "coronella-austriaca-sandro-2",
    "width": 1330,
    "height": 960,
    "widths": [
      400,
      800,
      1200,
      1330
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-sandro-3.jpg": {
    "path": "coronella-austriaca-sandro-3",
    "width": 2048,
    "height": 1614,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-sandro-4.jpg": {
    "path": "coronella-austriaca-sandro-4",
    "width": 1244,
    "height": 960,
    "widths": [
      400,
      800,
      1200,
      1244
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-shota-1.jpg": {
    "path": "coronella-austriaca-shota-1",
    "width": 767,
    "height": 1024,
    "widths": [
      400,
      767
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-zauri-1.jpg": {
    "path": "coronella-austriaca-zauri-1",
    "width": 1024,
    "height": 600,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-zauri-2.jpg": {
    "path": "coronella-austriaca-zauri-2",
    "width": 1024,
    "height": 786,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca-zauri-3.jpg": {
    "path": "coronella-austriaca-zauri-3",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/coronella-austriaca.webp": {
    "path": "coronella-austriaca",
    "width": 2200,
    "height": 1466,
    "widths": [
      400,
      800,
      1200,
      2200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/cuculus-canorus-chick-1.jpg": {
    "path": "cuculus-canorus-chick-1",
    "width": 1160,
    "height": 870,
    "widths": [
      400,
      800,
      1160
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/cuculus-canorus-eichler-1.jpg": {
    "path": "cuculus-canorus-eichler-1",
    "width": 1383,
    "height": 1261,
    "widths": [
      400,
      800,
      1200,
      1383
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/cuculus-canorus-janssen-1.jpg": {
    "path": "cuculus-canorus-janssen-1",
    "width": 1625,
    "height": 1083,
    "widths": [
      400,
      800,
      1200,
      1625
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/cuculus-canorus-moeller-1.jpg": {
    "path": "cuculus-canorus-moeller-1",
    "width": 1643,
    "height": 2191,
    "widths": [
      400,
      800,
      1200,
      1643
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/cuculus-canorus-morffew-1.jpg": {
    "path": "cuculus-canorus-morffew-1",
    "width": 2400,
    "height": 1920,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/cuculus-canorus-rinaud-1.jpg": {
    "path": "cuculus-canorus-rinaud-1",
    "width": 2000,
    "height": 2758,
    "widths": [
      400,
      800,
      1200,
      2000
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/cuculus-canorus-zauri-1.jpg": {
    "path": "cuculus-canorus-zauri-1",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-adjarica-2.jpg": {
    "path": "darevskia-adjarica-2",
    "width": 715,
    "height": 1204,
    "widths": [
      400,
      715
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-adjarica-3.jpg": {
    "path": "darevskia-adjarica-3",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-adjarica-mobile.jpg": {
    "path": "darevskia-adjarica-mobile",
    "width": 2048,
    "height": 1367,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-adjarica.jpg": {
    "path": "darevskia-adjarica",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-alpina-2.jpg": {
    "path": "darevskia-alpina-2",
    "width": 1650,
    "height": 1100,
    "widths": [
      400,
      800,
      1200,
      1650
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-alpina-3.jpg": {
    "path": "darevskia-alpina-3",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-alpina.jpg": {
    "path": "darevskia-alpina",
    "width": 1201,
    "height": 1596,
    "widths": [
      400,
      800,
      1200,
      1201
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-armeniaca-2.jpg": {
    "path": "darevskia-armeniaca-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-armeniaca-3.jpg": {
    "path": "darevskia-armeniaca-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-armeniaca-mobile.jpg": {
    "path": "darevskia-armeniaca-mobile",
    "width": 2048,
    "height": 1540,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-armeniaca.jpg": {
    "path": "darevskia-armeniaca",
    "width": 900,
    "height": 826,
    "widths": [
      400,
      800,
      900
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-brauneri-2.jpg": {
    "path": "darevskia-brauneri-2",
    "width": 1365,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1365
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-brauneri-3.jpg": {
    "path": "darevskia-brauneri-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-brauneri-mobile.jpg": {
    "path": "darevskia-brauneri-mobile",
    "width": 2048,
    "height": 1363,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-brauneri.jpg": {
    "path": "darevskia-brauneri",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-caucasica-2.jpg": {
    "path": "darevskia-caucasica-2",
    "width": 900,
    "height": 600,
    "widths": [
      400,
      800,
      900
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-caucasica-3.jpg": {
    "path": "darevskia-caucasica-3",
    "width": 960,
    "height": 720,
    "widths": [
      400,
      800,
      960
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-caucasica-mobile.jpg": {
    "path": "darevskia-caucasica-mobile",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-caucasica.jpg": {
    "path": "darevskia-caucasica",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-clarkorum-2.jpg": {
    "path": "darevskia-clarkorum-2",
    "width": 1112,
    "height": 1639,
    "widths": [
      400,
      800,
      1112
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-clarkorum-3.jpg": {
    "path": "darevskia-clarkorum-3",
    "width": 1728,
    "height": 1296,
    "widths": [
      400,
      800,
      1200,
      1728
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-clarkorum-mobile.jpg": {
    "path": "darevskia-clarkorum-mobile",
    "width": 2048,
    "height": 1538,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-clarkorum.jpg": {
    "path": "darevskia-clarkorum",
    "width": 2048,
    "height": 2041,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-daghestanica-2.jpg": {
    "path": "darevskia-daghestanica-2",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-daghestanica-3.jpg": {
    "path": "darevskia-daghestanica-3",
    "width": 1366,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1366
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-daghestanica.jpg": {
    "path": "darevskia-daghestanica",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-dahli-2.jpg": {
    "path": "darevskia-dahli-2",
    "width": 2048,
    "height": 1537,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-dahli-3.jpg": {
    "path": "darevskia-dahli-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-dahli.jpg": {
    "path": "darevskia-dahli",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-derjugini-2.jpg": {
    "path": "darevskia-derjugini-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-derjugini-3.jpg": {
    "path": "darevskia-derjugini-3",
    "width": 1616,
    "height": 1080,
    "widths": [
      400,
      800,
      1200,
      1616
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-derjugini-zauri-1.jpg": {
    "path": "darevskia-derjugini-zauri-1",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-derjugini-zauri-2.jpg": {
    "path": "darevskia-derjugini-zauri-2",
    "width": 1024,
    "height": 730,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-derjugini-zauri-3.jpg": {
    "path": "darevskia-derjugini-zauri-3",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-derjugini-zauri-4.jpg": {
    "path": "darevskia-derjugini-zauri-4",
    "width": 1024,
    "height": 680,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-derjugini.jpg": {
    "path": "darevskia-derjugini",
    "width": 2048,
    "height": 1268,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-mixta-2.jpg": {
    "path": "darevskia-mixta-2",
    "width": 1728,
    "height": 1296,
    "widths": [
      400,
      800,
      1200,
      1728
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-mixta-3.jpg": {
    "path": "darevskia-mixta-3",
    "width": 1728,
    "height": 1296,
    "widths": [
      400,
      800,
      1200,
      1728
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-mixta-mobile.jpg": {
    "path": "darevskia-mixta-mobile",
    "width": 2048,
    "height": 1413,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-mixta.jpg": {
    "path": "darevskia-mixta",
    "width": 1728,
    "height": 1296,
    "widths": [
      400,
      800,
      1200,
      1728
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-obscura-2.jpg": {
    "path": "darevskia-obscura-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-obscura-3.jpg": {
    "path": "darevskia-obscura-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-obscura-mobile.jpg": {
    "path": "darevskia-obscura-mobile",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-obscura.jpg": {
    "path": "darevskia-obscura",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-pontica-2.jpg": {
    "path": "darevskia-pontica-2",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-pontica-3.jpg": {
    "path": "darevskia-pontica-3",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-pontica-mobile.jpg": {
    "path": "darevskia-pontica-mobile",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-pontica.jpg": {
    "path": "darevskia-pontica",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-portschinskii-2.jpg": {
    "path": "darevskia-portschinskii-2",
    "width": 2048,
    "height": 1709,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-portschinskii-3.jpg": {
    "path": "darevskia-portschinskii-3",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-portschinskii-mobile.jpg": {
    "path": "darevskia-portschinskii-mobile",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-portschinskii.jpg": {
    "path": "darevskia-portschinskii",
    "width": 2048,
    "height": 1842,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-praticola-2.jpg": {
    "path": "darevskia-praticola-2",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-praticola-3.jpg": {
    "path": "darevskia-praticola-3",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-praticola-mobile.jpg": {
    "path": "darevskia-praticola-mobile",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-praticola.jpg": {
    "path": "darevskia-praticola",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-raddei-2.jpg": {
    "path": "darevskia-raddei-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-raddei-3.jpg": {
    "path": "darevskia-raddei-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-raddei-mobile.jpg": {
    "path": "darevskia-raddei-mobile",
    "width": 2048,
    "height": 1362,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-raddei.jpg": {
    "path": "darevskia-raddei",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-valentini-2.jpg": {
    "path": "darevskia-valentini-2",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-valentini-3.jpg": {
    "path": "darevskia-valentini-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/darevskia-valentini.jpg": {
    "path": "darevskia-valentini",
    "width": 1153,
    "height": 2048,
    "widths": [
      400,
      800,
      1153
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-caspius-2.jpg": {
    "path": "dolichophis-caspius-2",
    "width": 1262,
    "height": 1893,
    "widths": [
      400,
      800,
      1200,
      1262
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-caspius-3.jpg": {
    "path": "dolichophis-caspius-3",
    "width": 2048,
    "height": 1366,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-caspius.jpg": {
    "path": "dolichophis-caspius",
    "width": 1600,
    "height": 1200,
    "widths": [
      400,
      800,
      1200,
      1600
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-schmidti-2.webp": {
    "path": "dolichophis-schmidti-2",
    "width": 2048,
    "height": 1189,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-schmidti-3.webp": {
    "path": "dolichophis-schmidti-3",
    "width": 1200,
    "height": 1600,
    "widths": [
      400,
      800,
      1200
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-schmidti-4.webp": {
    "path": "dolichophis-schmidti-4",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-schmidti-6.webp": {
    "path": "dolichophis-schmidti-6",
    "width": 1920,
    "height": 1080,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-schmidti-7.webp": {
    "path": "dolichophis-schmidti-7",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/dolichophis-schmidti-mobile.webp": {
    "path": "dolichophis-schmidti-mobile",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-2.jpg": {
    "path": "eirenis-collaris-2",
    "width": 738,
    "height": 1600,
    "widths": [
      400,
      738
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-3.jpg": {
    "path": "eirenis-collaris-3",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-ioane-1.jpg": {
    "path": "eirenis-collaris-ioane-1",
    "width": 1024,
    "height": 771,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-ioane-2.jpg": {
    "path": "eirenis-collaris-ioane-2",
    "width": 771,
    "height": 1024,
    "widths": [
      400,
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-ioane-3.jpg": {
    "path": "eirenis-collaris-ioane-3",
    "width": 771,
    "height": 1024,
    "widths": [
      400,
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-nika-1.jpg": {
    "path": "eirenis-collaris-nika-1",
    "width": 879,
    "height": 912,
    "widths": [
      400,
      800,
      879
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-nika-2.jpg": {
    "path": "eirenis-collaris-nika-2",
    "width": 551,
    "height": 914,
    "widths": [
      400,
      551
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-nika-3.jpg": {
    "path": "eirenis-collaris-nika-3",
    "width": 1024,
    "height": 874,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-nika-4.jpg": {
    "path": "eirenis-collaris-nika-4",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris-nika-5.jpg": {
    "path": "eirenis-collaris-nika-5",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-collaris.jpg": {
    "path": "eirenis-collaris",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-modestus-2.jpg": {
    "path": "eirenis-modestus-2",
    "width": 344,
    "height": 260,
    "widths": [
      344
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-modestus-3.jpg": {
    "path": "eirenis-modestus-3",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-modestus-andro-1.jpg": {
    "path": "eirenis-modestus-andro-1",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-modestus-giorgi-1.jpg": {
    "path": "eirenis-modestus-giorgi-1",
    "width": 1024,
    "height": 685,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-modestus-mobile.jpg": {
    "path": "eirenis-modestus-mobile",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-modestus-papuna-1.jpg": {
    "path": "eirenis-modestus-papuna-1",
    "width": 768,
    "height": 1024,
    "widths": [
      400,
      768
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-modestus-zakro-1.jpg": {
    "path": "eirenis-modestus-zakro-1",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eirenis-modestus.jpg": {
    "path": "eirenis-modestus",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-dione-2.jpg": {
    "path": "elaphe-dione-2",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-dione-3.jpg": {
    "path": "elaphe-dione-3",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-dione-5.jpg": {
    "path": "elaphe-dione-5",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-dione-6.jpg": {
    "path": "elaphe-dione-6",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-dione-7.jpg": {
    "path": "elaphe-dione-7",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-dione-mobile.jpg": {
    "path": "elaphe-dione-mobile",
    "width": 1800,
    "height": 1200,
    "widths": [
      400,
      800,
      1200,
      1800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica-2.webp": {
    "path": "elaphe-urartica-2",
    "width": 2400,
    "height": 1599,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica-3.webp": {
    "path": "elaphe-urartica-3",
    "width": 2400,
    "height": 1602,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica-4.webp": {
    "path": "elaphe-urartica-4",
    "width": 2400,
    "height": 1350,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica-5.webp": {
    "path": "elaphe-urartica-5",
    "width": 1800,
    "height": 2400,
    "widths": [
      400,
      800,
      1200,
      1800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica-6.webp": {
    "path": "elaphe-urartica-6",
    "width": 2400,
    "height": 1800,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica-7.webp": {
    "path": "elaphe-urartica-7",
    "width": 1800,
    "height": 2400,
    "widths": [
      400,
      800,
      1200,
      1800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica-ioane-1.jpg": {
    "path": "elaphe-urartica-ioane-1",
    "width": 1080,
    "height": 1434,
    "widths": [
      400,
      800,
      1080
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica-mobile.webp": {
    "path": "elaphe-urartica-mobile",
    "width": 899,
    "height": 1600,
    "widths": [
      400,
      800,
      899
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/elaphe-urartica.webp": {
    "path": "elaphe-urartica",
    "width": 2400,
    "height": 1599,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/emberiza-citrinella-gailhampshire-1.jpg": {
    "path": "emberiza-citrinella-gailhampshire-1",
    "width": 1920,
    "height": 1643,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/emberiza-citrinella-gorbunova-1.jpg": {
    "path": "emberiza-citrinella-gorbunova-1",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/emberiza-citrinella-lours-1.jpg": {
    "path": "emberiza-citrinella-lours-1",
    "width": 1920,
    "height": 2652,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/emberiza-citrinella-sharp-1.jpg": {
    "path": "emberiza-citrinella-sharp-1",
    "width": 1559,
    "height": 1559,
    "widths": [
      400,
      800,
      1200,
      1559
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/emberiza-citrinella-trepte-1.jpg": {
    "path": "emberiza-citrinella-trepte-1",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/emberiza-citrinella-zauri-1.jpg": {
    "path": "emberiza-citrinella-zauri-1",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/emys-orbicularis-2.jpg": {
    "path": "emys-orbicularis-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/emys-orbicularis-3.jpg": {
    "path": "emys-orbicularis-3",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/emys-orbicularis.jpg": {
    "path": "emys-orbicularis",
    "width": 2048,
    "height": 1366,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eremias-arguta-2.jpg": {
    "path": "eremias-arguta-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/eremias-arguta-3.jpg": {
    "path": "eremias-arguta-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/eremias-arguta-mobile.jpg": {
    "path": "eremias-arguta-mobile",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eremias-arguta.jpg": {
    "path": "eremias-arguta",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eremias-velox-2.jpg": {
    "path": "eremias-velox-2",
    "width": 1280,
    "height": 853,
    "widths": [
      400,
      800,
      1200,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eremias-velox-3.jpg": {
    "path": "eremias-velox-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/eremias-velox-mobile.jpg": {
    "path": "eremias-velox-mobile",
    "width": 2048,
    "height": 1306,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/eremias-velox.jpg": {
    "path": "eremias-velox",
    "width": 2048,
    "height": 1152,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/erinaceus-concolor-1.jpg": {
    "path": "erinaceus-concolor-1",
    "width": 2400,
    "height": 1800,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/erinaceus-concolor-2.jpg": {
    "path": "erinaceus-concolor-2",
    "width": 2048,
    "height": 1897,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/erinaceus-concolor-3.jpg": {
    "path": "erinaceus-concolor-3",
    "width": 2048,
    "height": 1044,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/erinaceus-concolor-4.jpg": {
    "path": "erinaceus-concolor-4",
    "width": 1024,
    "height": 768,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/erinaceus-concolor-israel-1.jpg": {
    "path": "erinaceus-concolor-israel-1",
    "width": 2272,
    "height": 1704,
    "widths": [
      400,
      800,
      1200,
      2272
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/erinaceus-concolor-orkhevi-1.jpg": {
    "path": "erinaceus-concolor-orkhevi-1",
    "width": 2088,
    "height": 4640,
    "widths": [
      400,
      800,
      1200,
      2088
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eryx-jaculus-2.jpg": {
    "path": "eryx-jaculus-2",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eryx-jaculus-3.jpg": {
    "path": "eryx-jaculus-3",
    "width": 800,
    "height": 537,
    "widths": [
      400,
      800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eryx-jaculus-giorgi-1.jpg": {
    "path": "eryx-jaculus-giorgi-1",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eryx-jaculus-ioane-1.jpg": {
    "path": "eryx-jaculus-ioane-1",
    "width": 771,
    "height": 1024,
    "widths": [
      400,
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eryx-jaculus-ioane-2.jpg": {
    "path": "eryx-jaculus-ioane-2",
    "width": 771,
    "height": 1024,
    "widths": [
      400,
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eryx-jaculus-ioane-3.jpg": {
    "path": "eryx-jaculus-ioane-3",
    "width": 771,
    "height": 1024,
    "widths": [
      400,
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eryx-jaculus.jpg": {
    "path": "eryx-jaculus",
    "width": 1080,
    "height": 810,
    "widths": [
      400,
      800,
      1080
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/eumeces-schneiderii-2.jpg": {
    "path": "eumeces-schneiderii-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/eumeces-schneiderii-3.jpg": {
    "path": "eumeces-schneiderii-3",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/eumeces-schneiderii-mobile.jpg": {
    "path": "eumeces-schneiderii-mobile",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/eumeces-schneiderii.jpg": {
    "path": "eumeces-schneiderii",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-crowbared-1.jpg": {
    "path": "ficedula-hypoleuca-crowbared-1",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-lapa-1.jpg": {
    "path": "ficedula-hypoleuca-lapa-1",
    "width": 2400,
    "height": 1615,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-lepik-1.jpg": {
    "path": "ficedula-hypoleuca-lepik-1",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-rinaud-1.jpg": {
    "path": "ficedula-hypoleuca-rinaud-1",
    "width": 2400,
    "height": 1600,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-sharp-1.jpg": {
    "path": "ficedula-hypoleuca-sharp-1",
    "width": 1800,
    "height": 1200,
    "widths": [
      400,
      800,
      1200,
      1800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-strzelecki-1.jpg": {
    "path": "ficedula-hypoleuca-strzelecki-1",
    "width": 1620,
    "height": 1080,
    "widths": [
      400,
      800,
      1200,
      1620
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-virtala-1.jpg": {
    "path": "ficedula-hypoleuca-virtala-1",
    "width": 1398,
    "height": 2079,
    "widths": [
      400,
      800,
      1200,
      1398
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-zauri-1.jpg": {
    "path": "ficedula-hypoleuca-zauri-1",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-zauri-2.jpg": {
    "path": "ficedula-hypoleuca-zauri-2",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-hypoleuca-zauri-3.jpg": {
    "path": "ficedula-hypoleuca-zauri-3",
    "width": 1024,
    "height": 683,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-semitorquata-asman-1.jpg": {
    "path": "ficedula-semitorquata-asman-1",
    "width": 848,
    "height": 1272,
    "widths": [
      400,
      800,
      848
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-semitorquata-castro-1.jpg": {
    "path": "ficedula-semitorquata-castro-1",
    "width": 716,
    "height": 670,
    "widths": [
      400,
      716
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ficedula-semitorquata-medenica-1.jpg": {
    "path": "ficedula-semitorquata-medenica-1",
    "width": 1400,
    "height": 1050,
    "widths": [
      400,
      800,
      1200,
      1400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/hemorrhois-ravergieri-2.jpg": {
    "path": "hemorrhois-ravergieri-2",
    "width": 1790,
    "height": 1195,
    "widths": [
      400,
      800,
      1200,
      1790
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/hemorrhois-ravergieri-3.jpg": {
    "path": "hemorrhois-ravergieri-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/hemorrhois-ravergieri-mobile.jpg": {
    "path": "hemorrhois-ravergieri-mobile",
    "width": 1200,
    "height": 1600,
    "widths": [
      400,
      800,
      1200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/hemorrhois-ravergieri.jpg": {
    "path": "hemorrhois-ravergieri",
    "width": 2048,
    "height": 1151,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/hero-img.webp": {
    "path": "hero-img",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/hyla-orientalis-2.jpg": {
    "path": "hyla-orientalis-2",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/hyla-orientalis-3.jpg": {
    "path": "hyla-orientalis-3",
    "width": 1920,
    "height": 1280,
    "widths": [
      400,
      800,
      1200,
      1920
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/hyla-orientalis-mobile.jpg": {
    "path": "hyla-orientalis-mobile",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/hyla-orientalis.jpg": {
    "path": "hyla-orientalis",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/hyla-savignyi-2.jpg": {
    "path": "hyla-savignyi-2",
    "width": 1381,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1381
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/hyla-savignyi-3.jpg": {
    "path": "hyla-savignyi-3",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/hyla-savignyi-mobile.jpg": {
    "path": "hyla-savignyi-mobile",
    "width": 1500,
    "height": 1000,
    "widths": [
      400,
      800,
      1200,
      1500
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/hyla-savignyi.jpg": {
    "path": "hyla-savignyi",
    "width": 1331,
    "height": 1500,
    "widths": [
      400,
      800,
      1200,
      1331
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "/images/species/aegolius-funereus-moning-1.jpg": {
    "path": "images/species/aegolius-funereus-moning-1",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "/images/species/aegolius-funereus-tencate-1.jpg": {
    "path": "images/species/aegolius-funereus-tencate-1",
    "width": 2127,
    "height": 2569,
    "widths": [
      400,
      800,
      1200,
      2127
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "/images/species/aegolius-funereus-tencate-cavity-1.jpg": {
    "path": "images/species/aegolius-funereus-tencate-cavity-1",
    "width": 2400,
    "height": 1842,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "/images/species/aegolius-funereus-veronesi-1.jpg": {
    "path": "images/species/aegolius-funereus-veronesi-1",
    "width": 766,
    "height": 1100,
    "widths": [
      400,
      766
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-chorokhi-1.jpg": {
    "path": "jynx-torquilla-chorokhi-1",
    "width": 800,
    "height": 519,
    "widths": [
      400,
      800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-dalous-1.jpg": {
    "path": "jynx-torquilla-dalous-1",
    "width": 2400,
    "height": 1599,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-hobern-1.jpg": {
    "path": "jynx-torquilla-hobern-1",
    "width": 2400,
    "height": 1685,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-reigada-1.jpg": {
    "path": "jynx-torquilla-reigada-1",
    "width": 1936,
    "height": 1936,
    "widths": [
      400,
      800,
      1200,
      1936
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-ronning-1.jpg": {
    "path": "jynx-torquilla-ronning-1",
    "width": 2400,
    "height": 1604,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-shrestha-1.jpg": {
    "path": "jynx-torquilla-shrestha-1",
    "width": 2400,
    "height": 3361,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-zauri-1.jpg": {
    "path": "jynx-torquilla-zauri-1",
    "width": 1024,
    "height": 681,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-zauri-2.jpg": {
    "path": "jynx-torquilla-zauri-2",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-zauri-3.jpg": {
    "path": "jynx-torquilla-zauri-3",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/jynx-torquilla-zauri-4.jpg": {
    "path": "jynx-torquilla-zauri-4",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-agilis-2.jpg": {
    "path": "lacerta-agilis-2",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-agilis-3.jpg": {
    "path": "lacerta-agilis-3",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-agilis-mobile.jpg": {
    "path": "lacerta-agilis-mobile",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-agilis-sandro-1.jpg": {
    "path": "lacerta-agilis-sandro-1",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-agilis-sandro-2.jpg": {
    "path": "lacerta-agilis-sandro-2",
    "width": 1024,
    "height": 648,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-agilis.jpg": {
    "path": "lacerta-agilis",
    "width": 1600,
    "height": 1200,
    "widths": [
      400,
      800,
      1200,
      1600
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-media-2.jpg": {
    "path": "lacerta-media-2",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-media-3.jpg": {
    "path": "lacerta-media-3",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-media.jpg": {
    "path": "lacerta-media",
    "width": 858,
    "height": 570,
    "widths": [
      400,
      800,
      858
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-strigata-2.jpg": {
    "path": "lacerta-strigata-2",
    "width": 1696,
    "height": 1273,
    "widths": [
      400,
      800,
      1200,
      1696
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-strigata-3.jpg": {
    "path": "lacerta-strigata-3",
    "width": 2048,
    "height": 1148,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lacerta-strigata.jpg": {
    "path": "lacerta-strigata",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/landing-cta-cover.jpeg": {
    "path": "landing-cta-cover",
    "width": 1200,
    "height": 800,
    "widths": [
      400,
      800,
      1200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/lissotriton-lantzi-2.jpg": {
    "path": "lissotriton-lantzi-2",
    "width": 2048,
    "height": 1304,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lissotriton-lantzi-3.jpg": {
    "path": "lissotriton-lantzi-3",
    "width": 1485,
    "height": 1637,
    "widths": [
      400,
      800,
      1200,
      1485
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lissotriton-lantzi-mobile.jpg": {
    "path": "lissotriton-lantzi-mobile",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lissotriton-lantzi.jpg": {
    "path": "lissotriton-lantzi",
    "width": 922,
    "height": 2048,
    "widths": [
      400,
      800,
      922
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/lutra-lutra-baranowski-1.jpg": {
    "path": "lutra-lutra-baranowski-1",
    "width": 2400,
    "height": 1500,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lutra-lutra-christensen-1.jpg": {
    "path": "lutra-lutra-christensen-1",
    "width": 2400,
    "height": 1607,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lutra-lutra-hokkanen-1.jpg": {
    "path": "lutra-lutra-hokkanen-1",
    "width": 2400,
    "height": 1800,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lutra-lutra-ibanez-1.jpg": {
    "path": "lutra-lutra-ibanez-1",
    "width": 2400,
    "height": 1359,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/lutra-lutra-spraint-1.jpg": {
    "path": "lutra-lutra-spraint-1",
    "width": 2400,
    "height": 3200,
    "widths": [
      400,
      800,
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-2.webp": {
    "path": "macrovipera-lebetina-2",
    "width": 1200,
    "height": 1265,
    "widths": [
      400,
      800,
      1200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-4.webp": {
    "path": "macrovipera-lebetina-4",
    "width": 1500,
    "height": 1000,
    "widths": [
      400,
      800,
      1200,
      1500
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-5.webp": {
    "path": "macrovipera-lebetina-5",
    "width": 1500,
    "height": 998,
    "widths": [
      400,
      800,
      1200,
      1500
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-6.webp": {
    "path": "macrovipera-lebetina-6",
    "width": 800,
    "height": 498,
    "widths": [
      400,
      800
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-giorgi-1.jpg": {
    "path": "macrovipera-lebetina-giorgi-1",
    "width": 1024,
    "height": 691,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-giorgi-2.jpg": {
    "path": "macrovipera-lebetina-giorgi-2",
    "width": 1024,
    "height": 698,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-ioane-1.jpg": {
    "path": "macrovipera-lebetina-ioane-1",
    "width": 771,
    "height": 1024,
    "widths": [
      400,
      771
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-ioane-2.jpg": {
    "path": "macrovipera-lebetina-ioane-2",
    "width": 771,
    "height": 1024,
    "widths": [
      400,
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-ioane-3.jpg": {
    "path": "macrovipera-lebetina-ioane-3",
    "width": 771,
    "height": 1024,
    "widths": [
      400,
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-nika-1.jpg": {
    "path": "macrovipera-lebetina-nika-1",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-nika-2.jpg": {
    "path": "macrovipera-lebetina-nika-2",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-nika-3.png": {
    "path": "macrovipera-lebetina-nika-3",
    "width": 1224,
    "height": 816,
    "widths": [
      400,
      800,
      1200,
      1224
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-nika-4.jpg": {
    "path": "macrovipera-lebetina-nika-4",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-nino-1.jpg": {
    "path": "macrovipera-lebetina-nino-1",
    "width": 767,
    "height": 1024,
    "widths": [
      400,
      767
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-nino-2.jpg": {
    "path": "macrovipera-lebetina-nino-2",
    "width": 767,
    "height": 1024,
    "widths": [
      400,
      767
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-shota-1.jpg": {
    "path": "macrovipera-lebetina-shota-1",
    "width": 767,
    "height": 1024,
    "widths": [
      400,
      767
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-shota-2.jpg": {
    "path": "macrovipera-lebetina-shota-2",
    "width": 767,
    "height": 1024,
    "widths": [
      400,
      767
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-zakro-1.jpg": {
    "path": "macrovipera-lebetina-zakro-1",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina-zakro-2.jpg": {
    "path": "macrovipera-lebetina-zakro-2",
    "width": 1000,
    "height": 667,
    "widths": [
      400,
      800,
      1000
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/macrovipera-lebetina.webp": {
    "path": "macrovipera-lebetina",
    "width": 1200,
    "height": 798,
    "widths": [
      400,
      800,
      1200
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/malpolon-insignitus-2.jpg": {
    "path": "malpolon-insignitus-2",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/malpolon-insignitus-3.jpg": {
    "path": "malpolon-insignitus-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/malpolon-insignitus-mobile.jpg": {
    "path": "malpolon-insignitus-mobile",
    "width": 2048,
    "height": 2008,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/malpolon-insignitus.jpg": {
    "path": "malpolon-insignitus",
    "width": 2048,
    "height": 1264,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mauremys-caspica-2.jpg": {
    "path": "mauremys-caspica-2",
    "width": 1583,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1583
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mauremys-caspica-3.jpg": {
    "path": "mauremys-caspica-3",
    "width": 2048,
    "height": 1473,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mauremys-caspica-mobile.jpg": {
    "path": "mauremys-caspica-mobile",
    "width": 2048,
    "height": 1536,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/mauremys-caspica.jpg": {
    "path": "mauremys-caspica",
    "width": 1463,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1463
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/meles-canescens-armenia-tracks-1.jpg": {
    "path": "meles-canescens-armenia-tracks-1",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/meles-canescens-bafra-1.jpg": {
    "path": "meles-canescens-bafra-1",
    "width": 2048,
    "height": 1365,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/meles-canescens-vashlovani-1.jpg": {
    "path": "meles-canescens-vashlovani-1",
    "width": 1024,
    "height": 680,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/meles-canescens-yalova-1.jpg": {
    "path": "meles-canescens-yalova-1",
    "width": 1152,
    "height": 2048,
    "widths": [
      400,
      800,
      1152
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-2.jpg": {
    "path": "mertensiella-caucasica-2",
    "width": 2048,
    "height": 1534,
    "widths": [
      400,
      800,
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-3.jpg": {
    "path": "mertensiella-caucasica-3",
    "width": 1536,
    "height": 2048,
    "widths": [
      400,
      800,
      1200,
      1536
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-armen-1.jpg": {
    "path": "mertensiella-caucasica-armen-1",
    "width": 1024,
    "height": 682,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-armen-2.jpg": {
    "path": "mertensiella-caucasica-armen-2",
    "width": 1024,
    "height": 635,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-armen-3.jpg": {
    "path": "mertensiella-caucasica-armen-3",
    "width": 1024,
    "height": 673,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-armen-4.jpg": {
    "path": "mertensiella-caucasica-armen-4",
    "width": 1024,
    "height": 614,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-giorgi-1.jpg": {
    "path": "mertensiella-caucasica-giorgi-1",
    "width": 1024,
    "height": 642,
    "widths": [
      400,
      800,
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-lasha-1.jpg": {
    "path": "mertensiella-caucasica-lasha-1",
    "width": 1024,
    "height": 763,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-sandro-1.jpg": {
    "path": "mertensiella-caucasica-sandro-1",
    "width": 1024,
    "height": 846,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-sandro-2.jpg": {
    "path": "mertensiella-caucasica-sandro-2",
    "width": 1024,
    "height": 848,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-sandro-3.jpg": {
    "path": "mertensiella-caucasica-sandro-3",
    "width": 1024,
    "height": 769,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-zauri-1.jpg": {
    "path": "mertensiella-caucasica-zauri-1",
    "width": 1024,
    "height": 682,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-zauri-2.jpg": {
    "path": "mertensiella-caucasica-zauri-2",
    "width": 1024,
    "height": 682,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica-zauri-3.jpg": {
    "path": "mertensiella-caucasica-zauri-3",
    "width": 1024,
    "height": 682,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mertensiella-caucasica.jpg": {
    "path": "mertensiella-caucasica",
    "width": 2048,
    "height": 1356,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mustela-nivalis-andrieux-1.jpg": {
    "path": "mustela-nivalis-andrieux-1",
    "width": 1184,
    "height": 1800,
    "widths": [
      1184
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mustela-nivalis-grazalema-1.jpg": {
    "path": "mustela-nivalis-grazalema-1",
    "width": 1800,
    "height": 1350,
    "widths": [
      1200,
      1800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mustela-nivalis-martin-bravo-1.jpg": {
    "path": "mustela-nivalis-martin-bravo-1",
    "width": 1800,
    "height": 1350,
    "widths": [
      1200,
      1800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mustela-nivalis-richenza-1.jpg": {
    "path": "mustela-nivalis-richenza-1",
    "width": 1800,
    "height": 1205,
    "widths": [
      1200,
      1800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mustela-nivalis-strzelecki-1.jpg": {
    "path": "mustela-nivalis-strzelecki-1",
    "width": 1800,
    "height": 1200,
    "widths": [
      1200,
      1800
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mustela-nivalis-zauri-1.jpg": {
    "path": "mustela-nivalis-zauri-1",
    "width": 1024,
    "height": 682,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/mustela-nivalis-zauri-2.jpg": {
    "path": "mustela-nivalis-zauri-2",
    "width": 1024,
    "height": 682,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix-2.jpg": {
    "path": "natrix-natrix-2",
    "width": 2400,
    "height": 1701,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix-3.jpg": {
    "path": "natrix-natrix-3",
    "width": 1920,
    "height": 1440,
    "widths": [
      1200,
      1920
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix-4.jpg": {
    "path": "natrix-natrix-4",
    "width": 2400,
    "height": 1500,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix-5.jpg": {
    "path": "natrix-natrix-5",
    "width": 2400,
    "height": 1600,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix-6.jpg": {
    "path": "natrix-natrix-6",
    "width": 2400,
    "height": 1800,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix-7.jpg": {
    "path": "natrix-natrix-7",
    "width": 2400,
    "height": 1600,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix-mobile.jpg": {
    "path": "natrix-natrix-mobile",
    "width": 1800,
    "height": 1200,
    "widths": [
      1200,
      1800
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix-zakro-1.jpg": {
    "path": "natrix-natrix-zakro-1",
    "width": 1024,
    "height": 682,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-natrix.jpg": {
    "path": "natrix-natrix",
    "width": 2400,
    "height": 1600,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-2.webp": {
    "path": "natrix-tessellata-2",
    "width": 800,
    "height": 533,
    "widths": [
      800
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-3.webp": {
    "path": "natrix-tessellata-3",
    "width": 800,
    "height": 533,
    "widths": [
      800
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-4.webp": {
    "path": "natrix-tessellata-4",
    "width": 2200,
    "height": 1434,
    "widths": [
      1200,
      2200
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-5.webp": {
    "path": "natrix-tessellata-5",
    "width": 800,
    "height": 521,
    "widths": [
      800
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-7.webp": {
    "path": "natrix-tessellata-7",
    "width": 800,
    "height": 533,
    "widths": [
      800
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-beka-1.jpg": {
    "path": "natrix-tessellata-beka-1",
    "width": 768,
    "height": 1024,
    "widths": [
      768
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-giorgi-1.jpg": {
    "path": "natrix-tessellata-giorgi-1",
    "width": 552,
    "height": 368,
    "widths": [
      552
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-ioane-1.jpg": {
    "path": "natrix-tessellata-ioane-1",
    "width": 771,
    "height": 1024,
    "widths": [
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-ioane-2.jpg": {
    "path": "natrix-tessellata-ioane-2",
    "width": 771,
    "height": 1024,
    "widths": [
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-ioane-3.jpg": {
    "path": "natrix-tessellata-ioane-3",
    "width": 771,
    "height": 1024,
    "widths": [
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-ioane-4.jpg": {
    "path": "natrix-tessellata-ioane-4",
    "width": 771,
    "height": 1024,
    "widths": [
      771
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-sandro-1.jpg": {
    "path": "natrix-tessellata-sandro-1",
    "width": 1024,
    "height": 812,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-sandro-2.jpg": {
    "path": "natrix-tessellata-sandro-2",
    "width": 1024,
    "height": 728,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/natrix-tessellata-shota-1.jpg": {
    "path": "natrix-tessellata-shota-1",
    "width": 767,
    "height": 1024,
    "widths": [
      767
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-2.jpg": {
    "path": "ommatotriton-ophryticus-2",
    "width": 2048,
    "height": 1384,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-3.jpg": {
    "path": "ommatotriton-ophryticus-3",
    "width": 2048,
    "height": 1365,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-mobile.jpg": {
    "path": "ommatotriton-ophryticus-mobile",
    "width": 2048,
    "height": 1536,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-sandro-1.jpg": {
    "path": "ommatotriton-ophryticus-sandro-1",
    "width": 1024,
    "height": 760,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-sandro-2.jpg": {
    "path": "ommatotriton-ophryticus-sandro-2",
    "width": 1024,
    "height": 756,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-sandro-3.jpg": {
    "path": "ommatotriton-ophryticus-sandro-3",
    "width": 1024,
    "height": 686,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-zauri-1.jpg": {
    "path": "ommatotriton-ophryticus-zauri-1",
    "width": 1024,
    "height": 683,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-zauri-2.jpg": {
    "path": "ommatotriton-ophryticus-zauri-2",
    "width": 1024,
    "height": 683,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-zauri-3.jpg": {
    "path": "ommatotriton-ophryticus-zauri-3",
    "width": 1024,
    "height": 683,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus-zauri-4.jpg": {
    "path": "ommatotriton-ophryticus-zauri-4",
    "width": 1024,
    "height": 682,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ommatotriton-ophryticus.jpg": {
    "path": "ommatotriton-ophryticus",
    "width": 1280,
    "height": 910,
    "widths": [
      1200,
      1280
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/ophisops-elegans.jpg": {
    "path": "ophisops-elegans",
    "width": 2048,
    "height": 1536,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/panthera-pardus-assaf-1.jpg": {
    "path": "panthera-pardus-assaf-1",
    "width": 2400,
    "height": 1800,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/panthera-pardus-burkhard-1.jpg": {
    "path": "panthera-pardus-burkhard-1",
    "width": 2240,
    "height": 1488,
    "widths": [
      1200,
      2240
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/panthera-pardus-burkhard-2.jpg": {
    "path": "panthera-pardus-burkhard-2",
    "width": 2240,
    "height": 1488,
    "widths": [
      1200,
      2240
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/panthera-pardus-museum-2.jpg": {
    "path": "panthera-pardus-museum-2",
    "width": 2400,
    "height": 1350,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/panthera-pardus-thunderjag-1.jpg": {
    "path": "panthera-pardus-thunderjag-1",
    "width": 2400,
    "height": 1800,
    "widths": [
      1200,
      2400
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/paralaudakia-caucasia-2.jpg": {
    "path": "paralaudakia-caucasia-2",
    "width": 1728,
    "height": 1296,
    "widths": [
      1200,
      1728
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/paralaudakia-caucasia-3.jpg": {
    "path": "paralaudakia-caucasia-3",
    "width": 1728,
    "height": 1296,
    "widths": [
      1200,
      1728
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/paralaudakia-caucasia-mobile.jpg": {
    "path": "paralaudakia-caucasia-mobile",
    "width": 1920,
    "height": 1280,
    "widths": [
      1200,
      1920
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/paralaudakia-caucasia-zakro-1.jpg": {
    "path": "paralaudakia-caucasia-zakro-1",
    "width": 1024,
    "height": 682,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/paralaudakia-caucasia.jpg": {
    "path": "paralaudakia-caucasia",
    "width": 2000,
    "height": 1375,
    "widths": [
      1200,
      2000
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/pelobates-syriacus-2.jpg": {
    "path": "pelobates-syriacus-2",
    "width": 2048,
    "height": 1365,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/pelobates-syriacus-3.jpg": {
    "path": "pelobates-syriacus-3",
    "width": 1536,
    "height": 2048,
    "widths": [
      1200,
      1536
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/pelobates-syriacus.jpg": {
    "path": "pelobates-syriacus",
    "width": 1920,
    "height": 1280,
    "widths": [
      1200,
      1920
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/pelodytes-caucasicus-2.jpg": {
    "path": "pelodytes-caucasicus-2",
    "width": 1866,
    "height": 2048,
    "widths": [
      1200,
      1866
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/pelodytes-caucasicus-3.jpg": {
    "path": "pelodytes-caucasicus-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/pelodytes-caucasicus-zauri-1.jpg": {
    "path": "pelodytes-caucasicus-zauri-1",
    "width": 1024,
    "height": 683,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/pelodytes-caucasicus-zauri-2.jpg": {
    "path": "pelodytes-caucasicus-zauri-2",
    "width": 1024,
    "height": 683,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/pelodytes-caucasicus-zauri-3.jpg": {
    "path": "pelodytes-caucasicus-zauri-3",
    "width": 1024,
    "height": 683,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/pelodytes-caucasicus-zauri-4.jpg": {
    "path": "pelodytes-caucasicus-zauri-4",
    "width": 1024,
    "height": 778,
    "widths": [
      1024
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/pelodytes-caucasicus.jpg": {
    "path": "pelodytes-caucasicus",
    "width": 2048,
    "height": 1440,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/pelophylax-ridibundus-2.jpg": {
    "path": "pelophylax-ridibundus-2",
    "width": 900,
    "height": 600,
    "widths": [
      900
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/pelophylax-ridibundus-3.jpg": {
    "path": "pelophylax-ridibundus-3",
    "width": 1977,
    "height": 1977,
    "widths": [
      1200,
      1977
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/pelophylax-ridibundus.jpg": {
    "path": "pelophylax-ridibundus",
    "width": 2048,
    "height": 1365,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif"
    ]
  },
  "https://cdn.reptiles.ge/phoenicolacerta-laevis-2.jpg": {
    "path": "phoenicolacerta-laevis-2",
    "width": 793,
    "height": 573,
    "widths": [
      793
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cdn.reptiles.ge/phoenicolacerta-laevis-3.jpg": {
    "path": "phoenicolacerta-laevis-3",
    "width": 2048,
    "height": 1536,
    "widths": [
      1200,
      2048
    ],
    "formats": [
      "avif",
      "webp"
    ]
  }
};
